#!/bin/bash

yes | sudo apt update
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-venv

git clone https://github.com/mjason98/coffeeAPI.git

python3 -m venv coffeeAPI/venv
source coffeeAPI/venv/bin/activate
pip install -r coffeeAPI/requirements.txt

echo -e "DB_NAME=coffee.db\nDB_USER_NAME=user\nDB_USER_PWD=ea654541-426a-409c-a1b3-4597a0ecbfee" > coffeeAPI/.env

sudo mv coffeeAPI/coffee.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl stop coffee
sudo systemctl daemon-reload
sudo systemctl enable coffee
sudo systemctl start coffee

