# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure SSH known hosts
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H ${{ secrets.IPADDR }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_KEY }}" > my_gh_key && chmod 600 my_gh_key
    - name: Copy files
      run: |
        scp -i my_gh_key coffee.service ubuntu@${{ secrets.IPADDR }}:
        scp -i my_gh_key init_data.py ubuntu@${{ secrets.IPADDR }}:
        scp -i my_gh_key app.py ubuntu@${{ secrets.IPADDR }}:
        scp -i my_gh_key requirements.txt ubuntu@${{ secrets.IPADDR }}:
        scp -r -i my_gh_key services ubuntu@${{ secrets.IPADDR }}:

        echo -e "DB_NAME=${{ secrets.DB_NAME }}\nDB_USER_NAME=${{ secrets.DB_USER }}\nDB_USER_PWD=${{ secrets.DB_PWD }}" > .env
        scp -r -i my_gh_key .env ubuntu@${{ secrets.IPADDR }}:
    - name: Run remote app
      run: |
        ssh -i my_gh_key ubuntu@${{ secrets.IPADDR }} << EOF
          rm -rf env
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          [ ! -f coffee.db ] && python init_data.py
        EOF

        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo mv coffee.service /etc/systemd/system
        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo systemctl daemon-reload
        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo systemctl stop coffee

        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo systemctl daemon-reload
        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo systemctl enable coffee
        ssh -l ubuntu -i my_gh_key ${{ secrets.IPADDR }} -C sudo systemctl start coffee
